"""Frozen contract layer.

This package has no intra-project dependencies beyond itself. Every other package in
``ccas`` imports from here; nothing here imports from them.
"""

from __future__ import annotations

from ccas.schemas.call_log import CallLog, DatasetSource, DtmfEvent, GoldLabels, Utterance
from ccas.schemas.common import (
    SCHEMA_VERSION,
    Channel,
    Frozen,
    JsonValue,
    RiskTier,
    SchemaVersion,
    Slug,
    Speaker,
    TraceContext,
    Urgency,
    VerificationLevel,
    utcnow,
)
from ccas.schemas.domain import (
    ComplianceProfile,
    ComplianceRegime,
    ConfidenceThresholds,
    DomainPack,
    PatternSpec,
    QueueSpec,
)
from ccas.schemas.escalation import EscalationDecision, HandoffReason
from ccas.schemas.eval import (
    EvalCase,
    EvalReport,
    JudgeDimension,
    JudgeScore,
    JudgeVerdict,
    MetricValue,
    ProviderParityResult,
)
from ccas.schemas.handoff import HandoffContext, NextBestAction, VerifiedIdentity
from ccas.schemas.llm import (
    Effort,
    LLMChunk,
    LLMRequest,
    LLMResponse,
    LLMUsage,
    Message,
    ModelBinding,
    ProviderName,
)
from ccas.schemas.pii import (
    PiiEntityType,
    RedactedText,
    RedactionReport,
    RedactionSpan,
    RedactionStatus,
    sha256_hex,
)
from ccas.schemas.session import (
    CallerContext,
    IntentPrediction,
    LatencyLedger,
    SentimentSnapshot,
    SessionOutcome,
    SessionState,
    SlotValue,
    Turn,
)
from ccas.schemas.taxonomy import (
    AutomationScore,
    EscalationPolicy,
    IntentNode,
    IntentTaxonomy,
    Quadrant,
    QuadrantThresholds,
    SlotSpec,
    SlotType,
    VolumeStats,
)
from ccas.schemas.tools import (
    RetryPolicy,
    ToolPayload,
    ToolRecord,
    ToolResult,
    ToolSpec,
    ToolStatus,
)

__all__ = [
    "SCHEMA_VERSION",
    "AutomationScore",
    "CallLog",
    "CallerContext",
    "Channel",
    "ComplianceProfile",
    "ComplianceRegime",
    "ConfidenceThresholds",
    "DatasetSource",
    "DomainPack",
    "DtmfEvent",
    "Effort",
    "EscalationDecision",
    "EscalationPolicy",
    "EvalCase",
    "EvalReport",
    "Frozen",
    "GoldLabels",
    "HandoffContext",
    "HandoffReason",
    "IntentNode",
    "IntentPrediction",
    "IntentTaxonomy",
    "JsonValue",
    "JudgeDimension",
    "JudgeScore",
    "JudgeVerdict",
    "LLMChunk",
    "LLMRequest",
    "LLMResponse",
    "LLMUsage",
    "LatencyLedger",
    "Message",
    "MetricValue",
    "ModelBinding",
    "NextBestAction",
    "PatternSpec",
    "PiiEntityType",
    "ProviderName",
    "ProviderParityResult",
    "Quadrant",
    "QuadrantThresholds",
    "QueueSpec",
    "RedactedText",
    "RedactionReport",
    "RedactionSpan",
    "RedactionStatus",
    "RetryPolicy",
    "RiskTier",
    "SchemaVersion",
    "SentimentSnapshot",
    "SessionOutcome",
    "SessionState",
    "SlotSpec",
    "SlotType",
    "SlotValue",
    "Slug",
    "Speaker",
    "ToolPayload",
    "ToolRecord",
    "ToolResult",
    "ToolSpec",
    "ToolStatus",
    "TraceContext",
    "Turn",
    "Urgency",
    "Utterance",
    "VerificationLevel",
    "VerifiedIdentity",
    "VolumeStats",
    "sha256_hex",
    "utcnow",
]
